Attempt

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -24,13 +24,6 @@ jobs: # Solo vamos a crear un job.
         run: poetry install
       - name: Testing
         run: poetry run pytest --junitxml=jest-junit.xml --cov=modeltools --cov-report=lcov --cov-report=xml  # para que devuelva el un ficheros con el formato adecuado para que el step de GitHub Actions pueda leerlo (ej. .lcov, .xml, ...).
-      - name: Test Report  # Generar informe de pytest y verlo en GH
-        uses: dorny/test-reporter@v1
-        if: success() || failure()  # run this step even if previous step failed
-        with:
-          name: Tests  # Name of the check run which will be created
-          path: jest-junit.xml  # Path to test results
-          reporter: java-junit  # Format of test results. Tiene que coincidir con "poetry run pytest"
       - name: Coverage Report
         uses: devmasx/coverage-check-action@v1.2.0  # % de mi código cubierto por tests. Medida complementaria a tests superados.
         with:
@@ -38,6 +31,13 @@ jobs: # Solo vamos a crear un job.
           result_path: coverage.lcov
           min_coverage: 90
           token: ${{ github.token }}
+      - name: Test Report  # Generar informe de pytest y verlo en GH
+        uses: dorny/test-reporter@v1
+        if: success() || failure()  # run this step even if previous step failed
+        with:
+          name: Tests  # Name of the check run which will be created
+          path: jest-junit.xml  # Path to test results
+          reporter: java-junit  # Format of test results. Tiene que coincidir con "poetry run pytest"
       - name: build 
         run: poetry build  # run ejecuta comando de consola en el repo. Comando para empaquetar con poetry.
       - name: Publish to GH Releases  # https://github.com/marketplace?type=: publish release. BEST: https://github.com/softprops/action-gh-release. VER: https://github.com/softprops/action-gh-release#-customizing
