deletion y coverage

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -26,19 +26,19 @@ jobs: # Solo vamos a crear un job.
         run: poetry run pytest --junitxml=jest-junit.xml --cov=modeltools --cov-report=lcov --cov-report=xml  # para que devuelva el un ficheros con el formato adecuado para que el step de GitHub Actions pueda leerlo (ej. .lcov, .xml, ...).
       - name: Test Report  # Generar informe de pytest y verlo en GH
         uses: dorny/test-reporter@v1
-        if: success() || failure()    # run this step even if previous step failed
+        if: success() || failure()  # run this step even if previous step failed
         with:
-          name: Test            # Name of the check run which will be created
-          path: jest-junit.xml    # Path to test results
-          reporter: java-junit        # Format of test results. Java unit tiene que coincidir con "poetry run pytest"
-        - name: Coverage Report  # % de mi código cubierto por tests. Medida complementaria a tests superados.
-        uses: devmasx/coverage-check-action@v1.2.0
+          name: Test  # Name of the check run which will be created
+          path: jest-junit.xml  # Path to test results
+          reporter: java-junit  # Format of test results. Java unit tiene que coincidir con "poetry run pytest"
+        uses: devmasx/coverage-check-action@v1.2.0  # name: Coverage Report # % de mi código cubierto por tests. Medida complementaria a tests superados.
         with:
           type: lcov
           result_path: coverage.lcov
           min_coverage: 90
           token: ${{ github.token }}
-      - run: poetry build  # run ejecuta comando de consola en el repo. Comando para empaquetar con poetry.
+      - name: build 
+        run: poetry build  # run ejecuta comando de consola en el repo. Comando para empaquetar con poetry.
       - name: Publish to GH Releases  # https://github.com/marketplace?type=: publish release. BEST: https://github.com/softprops/action-gh-release. VER: https://github.com/softprops/action-gh-release#-customizing
         if: startsWith(github.ref, 'refs/tags/v')  # para que solo se ejecute si etiquetamos el commit empezando por v
         uses: softprops/action-gh-release@v1
